spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/SeagullsRoom
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none


  jwt:
    secret: 64c90cb1c17a313a601ab37bd6cc4e8a558e86b01cea7d22738b6da8efda0cfa37209299dfaa6d57c678571a460041d42c07d5234196388a887d7bfb3bff409c
openai:
  model: gpt-4o
  api:
    key: token
    url: https://api.openai.com/v1/chat/completions

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never # init sql 실행 x