name: new3gull CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          # 사용하는 자바 버전 17
          java-version: '17'
          distribution: 'temurin'  


      - run: touch ./SeagullsRoom/src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./SeagullsRoom/src/main/resources/application.yml
      - run: cat ./SeagullsRoom/src/main/resources/application.yml

      # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./SeagullsRoom/gradlew
      
     # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./SeagullsRoom/gradlew

    # EC2에 접속하고 배포합니다.
      - name: Deploy to Prod WAS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          # docker-compose가 있는 디렉토리로 이동해야 수행됩니다.
          script: |
            cd /home/ubuntu/Mocacong-Backend/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker-compose up -d
            sudo docker image prune -f
